//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TransportesMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cargamento
    {
        public int id_cargamento { get; set; }
        public int ruta_id { get; set; }
        public string descripcion { get; set; }
        public double peso { get; set; }
        public string estatus { get; set; }
    
        public virtual rutas rutas { get; set; }
    }
}
