//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TransportesMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class choferes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public choferes()
        {
            this.rutas = new HashSet<rutas>();
        }
    
        public int id_chofer { get; set; }
        public string nombre { get; set; }
        public string apellido_Paterno { get; set; }
        public string apellido_Materno { get; set; }
        public string telefono { get; set; }
        public System.DateTime fecha_Nacimiento { get; set; }
        public string licencia { get; set; }
        public string url_foto { get; set; }
        public bool disponibilidad { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<rutas> rutas { get; set; }
    }
}
