//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TransportesMVC.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TransportesEntities : DbContext
    {
        public TransportesEntities()
            : base("name=TransportesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<bitacora_camiones> bitacora_camiones { get; set; }
        public virtual DbSet<bitacora_cargamento> bitacora_cargamento { get; set; }
        public virtual DbSet<bitacora_choferes> bitacora_choferes { get; set; }
        public virtual DbSet<bitacora_direcciones> bitacora_direcciones { get; set; }
        public virtual DbSet<bitacora_paises> bitacora_paises { get; set; }
        public virtual DbSet<bitacora_rutas> bitacora_rutas { get; set; }
        public virtual DbSet<bitacora_usuarios> bitacora_usuarios { get; set; }
        public virtual DbSet<camiones> camiones { get; set; }
        public virtual DbSet<cargamento> cargamento { get; set; }
        public virtual DbSet<choferes> choferes { get; set; }
        public virtual DbSet<direcciones> direcciones { get; set; }
        public virtual DbSet<rutas> rutas { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<usuarios> usuarios { get; set; }
    }
}
