//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TransportesMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class rutas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public rutas()
        {
            this.cargamento = new HashSet<cargamento>();
        }
    
        public int id_Ruta { get; set; }
        public int camion_id { get; set; }
        public Nullable<double> distancia { get; set; }
        public Nullable<System.DateTime> fecha_salida { get; set; }
        public Nullable<System.DateTime> fecha_llegada_estimada { get; set; }
        public Nullable<System.DateTime> fecha_llegada_real { get; set; }
        public Nullable<int> chofer_id { get; set; }
        public int direcciones_origen_id { get; set; }
        public int direcciones_destino_id { get; set; }
    
        public virtual camiones camiones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cargamento> cargamento { get; set; }
        public virtual choferes choferes { get; set; }
        public virtual direcciones direcciones { get; set; }
        public virtual direcciones direcciones1 { get; set; }
    }
}
